namespace ExampleProject.Models
{
    /* 
    Item Model : Items are tied to Samples by a SampleModelid - this property is automatically generated when the Sample table is created but explicitly stating the property in the model allows you to easily access the id of teh Sample an Item is related to  
    */
    public class ItemModel 
    {
        public int id{get;set;}
        /*
        property to tie an Item to a Sample, this property is automatically generated by default but can be explicitly set as well
        */
        public int SampleModelid{get;set;}
        public string title{get;set;}
        /*
        empty constructor used to create a Item object with the SampleModelid property set in the controller and the other properties set from a form
        */  
        public ItemModel()
        {
            
        }
    }
}
