// <auto-generated />
using System;
using ExampleProject.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExampleProject.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    [Migration("20201012164759_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ExampleProject.Models.ItemModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SampleModelid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("SampleModelid");

                    b.ToTable("ItemModel");
                });

            modelBuilder.Entity("ExampleProject.Models.SampleModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("sampleEnumType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sampleInteger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sampleString")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("ExampleProject.Models.ItemModel", b =>
                {
                    b.HasOne("ExampleProject.Models.SampleModel", null)
                        .WithMany("itemList")
                        .HasForeignKey("SampleModelid");
                });
#pragma warning restore 612, 618
        }
    }
}
