// <auto-generated />
using ExampleProject.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExampleProject.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    partial class ExampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ExampleProject.Models.BucketModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("desc")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Buckets");
                });

            modelBuilder.Entity("ExampleProject.Models.ItemModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleModelid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("SampleModelid");

                    b.ToTable("ItemModel");
                });

            modelBuilder.Entity("ExampleProject.Models.SampleModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("sampleBucketID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sampleEnumType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sampleInteger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sampleString")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("ExampleProject.Models.ItemModel", b =>
                {
                    b.HasOne("ExampleProject.Models.SampleModel", null)
                        .WithMany("itemList")
                        .HasForeignKey("SampleModelid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
